# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KnowledgeTag(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tag ID
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tag name
    """

    type: typing.Optional[typing.Literal["knowledge"]] = pydantic.Field(default=None)
    """
    Tag type
    """

    binding_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Binding count
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
