# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .advanced_chat.client import AdvancedChatClient as advanced_chat_advanced_chat_client_AdvancedChatClient
from .advanced_chat.client import AsyncAdvancedChatClient as advanced_chat_advanced_chat_client_AsyncAdvancedChatClient
from .raw_client import AsyncRawAdvancedChatClient, RawAdvancedChatClient


class AdvancedChatClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAdvancedChatClient(client_wrapper=client_wrapper)
        self.advanced_chat = advanced_chat_advanced_chat_client_AdvancedChatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAdvancedChatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAdvancedChatClient
        """
        return self._raw_client


class AsyncAdvancedChatClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAdvancedChatClient(client_wrapper=client_wrapper)
        self.advanced_chat = advanced_chat_advanced_chat_client_AsyncAdvancedChatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAdvancedChatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAdvancedChatClient
        """
        return self._raw_client
