# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .generation.client import AsyncGenerationClient as generation_generation_client_AsyncGenerationClient
from .generation.client import GenerationClient as generation_generation_client_GenerationClient
from .raw_client import AsyncRawGenerationClient, RawGenerationClient


class GenerationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawGenerationClient(client_wrapper=client_wrapper)
        self.generation = generation_generation_client_GenerationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawGenerationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawGenerationClient
        """
        return self._raw_client


class AsyncGenerationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawGenerationClient(client_wrapper=client_wrapper)
        self.generation = generation_generation_client_AsyncGenerationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawGenerationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawGenerationClient
        """
        return self._raw_client
