# This file was auto-generated by Fern from our API Definition.

import typing

BadRequestErrorBodyCode = typing.Union[
    typing.Literal[
        "invalid_param",
        "app_unavailable",
        "provider_not_initialize",
        "provider_quota_exceeded",
        "model_currently_not_support",
        "workflow_not_found",
        "draft_workflow_error",
        "workflow_id_format_error",
        "completion_request_error",
    ],
    typing.Any,
]
