# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_history_message_feedback_rating import ChatHistoryMessageFeedbackRating


class ChatHistoryMessageFeedback(UniversalBaseModel):
    """
    Feedback information
    """

    rating: typing.Optional[ChatHistoryMessageFeedbackRating] = pydantic.Field(default=None)
    """
    Like or dislike rating
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
