# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ForbiddenErrorBody(UniversalBaseModel):
    code: typing.Optional[typing.Literal["file_access_denied"]] = None
    status: int = pydantic.Field()
    """
    HTTP status code
    """

    message: str = pydantic.Field()
    """
    Error message description
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
