# This file was auto-generated by Fern from our API Definition.

from .create_segments_request_segments_item import CreateSegmentsRequestSegmentsItem
from .create_segments_response import CreateSegmentsResponse
from .delete_segment_response import DeleteSegmentResponse
from .get_segments_response import GetSegmentsResponse
from .update_segment_request_segment import UpdateSegmentRequestSegment
from .update_segment_response import UpdateSegmentResponse

__all__ = [
    "CreateSegmentsRequestSegmentsItem",
    "CreateSegmentsResponse",
    "DeleteSegmentResponse",
    "GetSegmentsResponse",
    "UpdateSegmentRequestSegment",
    "UpdateSegmentResponse",
]
