# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from .types import (
    CreateSegmentsRequestSegmentsItem,
    CreateSegmentsResponse,
    GetDatasetsDatasetIdDocumentsDocumentIdSegmentsSegmentIdChildChunksResponse,
    GetSegmentsResponse,
    PatchDatasetsDatasetIdDocumentsDocumentIdSegmentsSegmentIdChildChunksChildChunkIdResponse,
    PostDatasetsDatasetIdDocumentsDocumentIdSegmentsSegmentIdChildChunksResponse,
    UpdateSegmentRequestSegment,
    UpdateSegmentResponse,
)

__all__ = [
    "CreateSegmentsRequestSegmentsItem",
    "CreateSegmentsResponse",
    "GetDatasetsDatasetIdDocumentsDocumentIdSegmentsSegmentIdChildChunksResponse",
    "GetSegmentsResponse",
    "PatchDatasetsDatasetIdDocumentsDocumentIdSegmentsSegmentIdChildChunksChildChunkIdResponse",
    "PostDatasetsDatasetIdDocumentsDocumentIdSegmentsSegmentIdChildChunksResponse",
    "UpdateSegmentRequestSegment",
    "UpdateSegmentResponse",
]
