# This file was auto-generated by Fern from our API Definition.

import typing

ChunkChatCompletionResponseEvent = typing.Union[
    typing.Literal["message", "message_end", "tts_message", "tts_message_end", "message_replace", "error", "ping"],
    typing.Any,
]
