# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_application_parameters_by_app_generation_response_file_upload_image import (
    GetApplicationParametersByAppGenerationResponseFileUploadImage,
)


class GetApplicationParametersByAppGenerationResponseFileUpload(UniversalBaseModel):
    """
    File upload configuration
    """

    image: typing.Optional[GetApplicationParametersByAppGenerationResponseFileUploadImage] = pydantic.Field(
        default=None
    )
    """
    Image settings
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
