# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_segment_detail_response_data import GetSegmentDetailResponseData


class GetSegmentDetailResponse(UniversalBaseModel):
    data: typing.Optional[GetSegmentDetailResponseData] = None
    doc_form: typing.Optional[str] = pydantic.Field(default=None)
    """
    Document form
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
